BOARD_TAG   = nano
BOARD_SUB   = atmega328

PWD = $(shell pwd)

USER_LIB_PATH = $(PWD)/lib
ARDUINO_LIBS = DHT-sensor-library Arduino-Temperature-Control-Library Adafruit_Sensor OneWire rc-switch TimerOne SPI Wire

include ./Arduino-Makefile/Arduino.mk

